// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChoosColor(arg1) {
  return window['go']['main']['App']['ChoosColor'](arg1);
}

export function Color(arg1) {
  return window['go']['main']['App']['Color'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
